# Base OS: Debian Linux
FROM tomcat:10.1-jdk17

# Remove default Tomcat apps
RUN rm -rf /usr/local/tomcat/webapps/*

# Copy WAR file
COPY target/user-creation-application-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war


# Expose Tomcat port
EXPOSE 8080

# Start Tomcat
CMD ["catalina.sh", "run"]
